package dev.ncc.mutualtransfer;

import android.view.View;
import android.view.ViewGroup;
import android.webkit.CookieManager;
import android.webkit.WebView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import java.io.*;
import java.net.URL;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;
import javax.net.ssl.HttpsURLConnection;
import org.json.JSONObject;
import org.junit.Test;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

/** Real emulator WebView + native TLS against the actual Node service.
 * File input is generated by the test, not a system document-provider acceptance. */
@RunWith(AndroidJUnit4.class)
public class HttpsExchangeTest {
    private <T> T find(View view, Class<T> type, String text) {
        if (type.isInstance(view) && (text == null || (view instanceof TextView && ((TextView)view).getText().toString().equals(text)))) return type.cast(view);
        if (view instanceof ViewGroup) for (int i = 0; i < ((ViewGroup)view).getChildCount(); i++) {
            T result = find(((ViewGroup)view).getChildAt(i), type, text); if (result != null) return result;
        }
        return null;
    }
    private String js(ActivityScenario<MainActivity> scenario, String script) throws Exception {
        CountDownLatch done = new CountDownLatch(1); AtomicReference<String> answer = new AtomicReference<>();
        scenario.onActivity(activity -> find(activity.getWindow().getDecorView(), WebView.class, null).evaluateJavascript(script, value -> { answer.set(value); done.countDown(); }));
        assertTrue("WebView did not answer", done.await(10, TimeUnit.SECONDS)); return answer.get();
    }
    private void waitJs(ActivityScenario<MainActivity> scenario, String script) throws Exception {
        long end = System.nanoTime() + TimeUnit.SECONDS.toNanos(60);
        while (System.nanoTime() < end) { if ("true".equals(js(scenario, script))) return; Thread.sleep(200); }
        fail("WebView condition did not become true (no credentials logged)");
    }
    @Test public void realHttpsLoginChunkUploadAndNativeVerifiedDownload() throws Exception {
        JSONObject config;
        try (InputStream input = InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("connection.json")) {
            config = new JSONObject(new String(input.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8));
        }
        String origin = config.getString("origin");
        assertTrue(InstrumentationRegistry.getInstrumentation().getTargetContext().getPackageName().endsWith(".acceptance"));
        try (ActivityScenario<MainActivity> scenario = ActivityScenario.launch(MainActivity.class)) {
            scenario.onActivity(activity -> {
                View root = activity.getWindow().getDecorView(); find(root, EditText.class, null).setText(origin);
                find(root, Button.class, "连接").performClick();
            });
            waitJs(scenario, "!!document.getElementById('login') && typeof document.getElementById('login').onsubmit === 'function'");
            assertEquals("true", js(scenario, "window.isSecureContext && !!crypto.subtle"));
            js(scenario, "document.getElementById('key').value=" + JSONObject.quote(config.getString("key")) + ";document.getElementById('login').requestSubmit();");
            waitJs(scenario, "!document.getElementById('workspace').hidden && document.getElementById('list').textContent.includes('server-fixture.bin')");
            // Exercise the shipped upload handler and its real two-chunk protocol.
            js(scenario, "(()=>{const bytes=new Uint8Array(4194304+65537);for(let i=0;i<bytes.length;i++)bytes[i]=i%251;const dt=new DataTransfer();dt.items.add(new File([bytes],'android-upload.bin'));const f=document.getElementById('files');f.files=dt.files;f.dispatchEvent(new Event('change'));})()");
            waitJs(scenario, "document.getElementById('status').textContent.includes('android-upload.bin 已上传并通过校验') && !document.getElementById('files').disabled");
            AtomicReference<String> cookie = new AtomicReference<>(); scenario.onActivity(a -> cookie.set(CookieManager.getInstance().getCookie(origin)));
            assertNotNull(cookie.get());
            HttpsURLConnection request = (HttpsURLConnection)new URL(origin + config.getString("download")).openConnection();
            request.setConnectTimeout(15000); request.setReadTimeout(15000); request.setInstanceFollowRedirects(false); request.setRequestProperty("Cookie", cookie.get());
            try {
                assertEquals(200, request.getResponseCode()); ByteArrayOutputStream output = new ByteArrayOutputStream();
                try (InputStream input = request.getInputStream()) {
                    assertEquals(65537, VerifiedDownload.copy(input, output, OriginPolicy.digest(request.getHeaderField("ETag")), request.getContentLengthLong(), () -> false));
                }
                assertEquals(config.getString("hash"), OriginPolicy.digest(request.getHeaderField("ETag")));
                byte[] data = output.toByteArray(); for (int i = 0; i < data.length; i++) assertEquals((byte)(i % 251), data[i]);
            } finally { request.disconnect(); }
            // Same issuer but absent localhost SAN must still fail name verification.
            HttpsURLConnection wrong = (HttpsURLConnection)new URL("https://127.0.0.1:10878/").openConnection();
            wrong.setConnectTimeout(5000); wrong.setReadTimeout(5000);
            try { wrong.getInputStream().close(); fail("Wrong certificate hostname accepted"); }
            catch (javax.net.ssl.SSLException expected) { /* ordinary hostname verification */ }
            finally { wrong.disconnect(); }
            try (android.os.ParcelFileDescriptor capture = InstrumentationRegistry.getInstrumentation().getUiAutomation()
                    .executeShellCommand("screencap -p /data/local/tmp/mutual-transfer-https.png");
                 FileInputStream completion = new FileInputStream(capture.getFileDescriptor())) {
                assertEquals(-1, completion.read());
            }
            scenario.onActivity(a -> find(a.getWindow().getDecorView(), Button.class, "断开并清理").performClick());
            long end = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
            do { scenario.onActivity(a -> cookie.set(CookieManager.getInstance().getCookie(origin))); if (cookie.get() == null) break; Thread.sleep(100); } while (System.nanoTime() < end);
            assertNull("Disconnect must clear the application's session cookie", cookie.get());
        }
    }
}
